"""Models for the Fumis WiRCU API."""


STATUS_OFF = "off"
STATUS_PRE_HEATING = "pre_heating"
STATUS_IGNITION = "ignition"
STATUS_COMBUSTION = "combustion"
STATUS_ECO = "eco"
STATUS_COOLING = "cooling"
STATUS_UNKNOWN = "unknown"
# wood start 1
STATUS_SCHEITHOLZSTART1 = "Scheitholzstart I"
# wood start 2
STATUS_SCHEITHOLZSTART2 = "Scheitholzstart II"
# operation mode wood
STATUS_SCHEITHOLZBETRIEB = "Scheitholzbetrieb"

STOVE_ID = 1
STOVE_BURN_ID = 7
PRESSURE_ID = 35
RPM_ID = 34


STATUS_MAPPING = {
    0: STATUS_OFF,
    10: STATUS_PRE_HEATING,
    20: STATUS_IGNITION,
    30: STATUS_COMBUSTION,
    40: STATUS_ECO,
    50: STATUS_COOLING,
    80: STATUS_SCHEITHOLZSTART1,
    100: STATUS_SCHEITHOLZSTART2,
    110: STATUS_SCHEITHOLZBETRIEB,
}

STATE_OFF = "off"
STATE_ON = "on"
STATE_UNKNOWN = "unknown"

STATE_MAPPING = {
    1: STATE_OFF,
    2: STATE_ON,
}

ECO_MAPPING = {
    0: STATE_OFF,
    1: STATE_ON,
}
